### ISSUE TITLE
accept the terms and subscribe to the AWS Marketplace product 

### ISSUE THREAD

**Issue by bagitte** [citrix/netscaler-aws-cloudformation#2]
The 'accept the terms and subscribe to the AWS Marketplace product' link doesn't seem to work.  Can that be fixed.  Thanks.

**Comment by sumanth-lingappa** [comment]
Yes, it will be corrected in a day @bagitte

**Comment by bagitte** [comment]
> Yes, it will be corrected in a day @bagitte

Thanks!
