### ISSUE TITLE
failed to add ip set on secondary netscaler

### ISSUE THREAD

**Issue by bagitte** [citrix/netscaler-aws-cloudformation#3]
I've attempted to run the CF template twice, in two separate AWS accounts, with the same result.  

Here's the error i'm encountering:

Failed to create custom resource ConfigureLambda in arn:aws:cloudformation:us-east-1:305261604435:stack/NetScalerVPX-HAPair-MZ/adecbc30-5a74-11e9-89df-0ea1c9c8db82 in response to 58442c69-4176-4460-89d2-60eaebdffd37: FAIL: Could not add IPSET ipset123

Please advise.  Thanks.

**Comment by sumanth-lingappa** [comment]
The CFT is working fine in our test environment. @bagitte  can you please tell more about your network setup?
BTW, have you fully followed the [prerequisite](https://github.com/citrix/netscaler-aws-cloudformation/tree/master/templates/ha_3_nic_mz#pre-requisites)?

Also, there will be logs in your cloudwatch. Can you please attach those here?

**Comment by bagitte** [comment]
Correct, we followed the preq.  We have a single VPC and two AZs for this setup:

Zone - east-1a
- Primary Management IP - 10.64.108.40
- Primary Management Subnet - 10.64.108.0/24 w/igw (public subnet)
- Primary Client IP - 10.64.108.41
- Primary Client Subnet - 10.64.108.0/24 w/igw (pubic subnet)
- Primary Server IP - 10.64.96.41
- Primary Server Subnet - 10.64.96.0/23 w/nat (private subnet)

Zone - east-1b

- Secondary Management IP - 10.64.109.40
- Seconary Management Subnet - 10.64.109.0/24 w/igw (public subnet)
- Secondary Client IP - 10.64.109.41
- Secondary Client Subnet - 10.64.109.0/24 w/igw (pubic subnet)
- Secondary Server IP - 10.64.98.41
- Seconary Server Subnet - 10.64.98.0/23 w/nat (private subnet)

Thanks.

**Comment by bagitte** [comment]
hi sumanth-lingappa - i see that the mutiple az ha template has been updated.  is this fixed?  can i test?  thanks.

**Comment by sumanth-lingappa** [comment]
Hi @bagitte , the last commit has only cosmetic changes. Nothing related to the functionality of the CFT.

Meanwhile, can you please change your subnets as below - 
1. I see your manangement subnet and client subnets are same.. -- I suspect this is the issue
2. As a recommendation, we always suggest to have different subnets to all management, client, server sides on each primary and secondary VPXs
3. Also the management subnets should not overlap the VPC starting CIDR. EG. if VPC CIDR is 10.0.0.0/16, then any subnets' CIDR shoud be anything other than 10.0.**0**.0/24

The same is mentioned in the citrix docs (https://docs.citrix.com/en-us/citrix-adc/12-1/deploying-vpx/deploy-aws/high-availability-different-zones.html)

> Citrix recommends that you use different subnets for management (NSIP), client traffic (VIP), and back-end server (SNIP).

I request you to please change these according, try and let us know.

**Comment by wpline** [comment]
Actually, they were all on different subnets initially; however, that would also fail as the management subnet was in a private subnet behind NAT.  For CFT to configure HA and other things, the mgmt subnet also needs to be a subnet with internet gateway, hence i moved mgmt to the client subnet.  After doing that, the process goes further but fails at adding the IP set.

**Comment by bagitte** [comment]
Hi @sumanth-lingappa, this time i attempted the setup mgmt, client, and server (both primary and secondary) IPs in the same subnet and availability zone but it also failed with the same ip set issue.  Not sure what else to try.  Any other recommedations.  Thanks.

**Comment by chiradeep** [comment]
Seems clear to me that the root cause is
```
add_ipset result {'http_response_data': {'url': 'https://3.208.245.90/nitro/v1/config/ipset', 'date': 'Tue, 09 Apr 2019 03:15:29 GMT', 'server': 'Apache', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'pragma': 'no-cache', 'content-length': '84', 'connection': 'close', 'content-type': 'application/json; charset=utf-8', 'msg': 'HTTP Error 401: Unauthorized', 'status': 401}, 'http_response_code': 0, 'nitro_errorcode': 354, 'nitro_message': 'Invalid username or password', 'nitro_severity': 'ERROR', 'data': {'errorcode': 354, 'message': 'Invalid username or password', 'severity': 'ERROR'}}```

Why is the lambda function using a wrong password? Or does the VPX not have the right password?

**Comment by bagitte** [comment]
@chiradeep please advise where or when should i set the password? I basically run the cloudformation template by inputting only the IPs and subnets.  Also, the lambda function seems to be able to add the HA nodes during the provisioning process, assuming using the same password.  The adding of the IP set occurs afterwards, on the secondary node.  Should the pw sync have already occurred between the two VPXs?  So, i'm not exactly sure if i need to manually intervene and set the password on the secondary vpx?  Should I do that?  But once lamda is unable to add the ip set to the secondary node, the roll back occurs right away.  I don't have a chance to intervene.  Please advise. Thanks.

**Comment by chiradeep** [comment]
@bagitte I don't think you need to add the password anywhere. This may be a logic or timing-related issue where passwords are not synced / set correctly.

**Comment by bagitte** [comment]
@chiradeep ok, thanks.  Assuming the lambda function can be tweaked to increase timeout, we'll await any new fixes.  But if there's anything i need do on my end, please advise.  Thanks.

**Comment by chiradeep** [comment]
I see this
```
[INFO]	2019-04-09T03:14:54.358Z	d2734ce0-6b23-444f-a4bf-2836d05c0778	Waiting for 30 seconds. Reason: secondary VPX password to get synced to that of primary
Waiting for 30 seconds. Reason: secondary VPX password to get synced to that of primary
[INFO]	2019-04-09T03:15:24.378Z	d2734ce0-6b23-444f-a4bf-2836d05c0778	Waiting for 3 seconds
Waiting for 3 seconds
```

Maybe the password sync didn't happen @sumanth-lingappa

**Comment by bagitte** [comment]
Hello @chiradeep and @sumanth-lingappa, just checking inn to see if there's any updates.  Thanks.

**Comment by sumanth-lingappa** [comment]
@bagitte : Please try now.

**Comment by bagitte** [comment]
@sumanth-lingappa unfortunately, it's now failing at adding HA node: 

Failed to create custom resource ConfigureLambda in arn:aws:cloudformation:us-east-1:317098396095:stack/NetScalerVPX-HAPair-MZ/7bcf43d0-650a-11e9-8749-126c686965ae in response to 77bd40c6-cba7-4667-bc6e-4f9e78083b32: FAIL: Could not add HA node for 52.5.140.54

Previously, HA node was able to be added but fails on adding IP set thereafter.  

Also, I noticed that i can no longer provision it for multiple AZs after the CFT update  I kept getting network resource in separate/different network  error, which is what we want for HA in multiple AZs.  To get around this for testing, i just used IPs from the same AZ.  Thanks.

**Comment by sumanth-lingappa** [comment]
@bagitte can you please provide your input parameters details, which you give in the parameters of CFT?
inputs such as - 

1. AWS region
2. VPC CIDR details
3. All subnets CIDR and the IP values filled in the CFT input parameter section
4. others, if any

I will try reproducing your error in my setup

Also, please provide the logs for your last run, preferably in a .zip file
Thank you

**Comment by bagitte** [comment]
@bagitte please see attached logs.

[000000.gz](https://github.com/citrix/netscaler-aws-cloudformation/files/3107875/000000.gz)

1) Region - US East (N. Virginia) (us-east-1)
2) VPC details - Both subnets are in the same VPC with the following:

AZ - 1a 

172.31.32.0/20 (subnet)
172.31.32.50
172.31.32.51
172.31.32.52

AZ - 1c  
172.31.0.0/20 (subnet)
172.31.0.50
172.31.0.51
172.31.0.52

Both subnets have access to the internet through IGW.  The IPs are listed in order of mgmt, client, and server.  Thanks.

**Comment by sumanth-lingappa** [comment]
@bagitte Thank you for the configuration. Can I also know the VPC CIDR block?
Thanks

**Comment by bagitte** [comment]
@sumanth-lingappa the VPC ipv4 cidr blcok is 172.31.0.0/16

**Comment by sumanth-lingappa** [comment]
Hi @bagitte , please find my comments:
with your network configuration (**all** management, client, servers side being in the **SAME** subnet), the traffic which had to be sent via management side, sometime routes via server or client in AWS and eventually the packets get dropped.

Hence it is recommended to have 3 different subnets for management, client and server side, for smoother packet transmission.

Also one more recommendation is VPC CIDR and any of the subnets' CIDR should not be overlaped.
Eg. If VPC is **10.0.0.0**/16, then its a recommendation NOT to have any subnets with **10.0.0.0**/**n**
Some of the valid subnets are **10.0.1.0/24**, **10.0.2.0/24** etc

The same had been told in earlier comment: https://github.com/citrix/netscaler-aws-cloudformation/issues/3#issuecomment-482432121

**Comment by bagitte** [comment]
@sumanth-lingappa our subnets are not overlapping.  Also, we tried using different subnets in the past but with the same results; hence, for simplicity sake, i put them on the same subnet.  if you think the vpc/subnet is the source of the problem, then we'll setup a brand new vpc and test again on different subnets.  Thanks.

**Comment by bagitte** [comment]
@sumanth-lingappa i didn't create a new vpc but i created a couple additional subnets.  In any event, the multiple az setup was successful.  I'm able to deploy the netscaler in two different AZs and failover/back. Thanks for your help.  We can close this issue.

**Comment by sumanth-lingappa** [comment]
Great to hear @bagitte 
Happy to help anytime.
