### ISSUE TITLE
Netscaler Cloud formation error

### ISSUE THREAD

**Issue by awsgit4** [citrix/netscaler-aws-cloudformation#4]
Receiving the below error running this template. Same issue occurred with netscaler for HA template.

API: ec2:RunInstances Not authorized for images: [ami-59f5c023]

**Comment by kaplian** [comment]
This is because you have not registered the AWS marketplace AMI(s) with the account you are using to deploy.  The AMI IDs will vary by region, you will need to register the AMI in the region in which you wish to deploy.

**Comment by sumanth-lingappa** [comment]
@kaplian : Thank you for helping @awsgit4 
@awsgit4 : I am closing this assuming you found out the solution.
