### ISSUE TITLE
Error on Lambda creation

### ISSUE THREAD

**Issue by kaplian** [citrix/netscaler-aws-cloudformation#5]
Stack repeatedly fails to proceed beyond the Lambda function creation.  Logs show a 401 while pulling a config file. 

save_config result {'http_response_data': {'url': 'https://108.128.174.85/nitro/v1/config/nsconfig?action=save', 'date': 'Tue, 04 Jun 2019 08:43:54 GMT', 'server': 'Apache', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'pragma': 'no-cache', 'content-length': '84', 'connection': 'close', 'content-type': 'application/json; charset=utf-8', 'msg': *'HTTP Error 401: Unauthorized', 'status': 401}, 'http_response_code': 0, 'nitro_errorcode': 354, 'nitro_message': 'Invalid username or password', 'nitro_severity': 'ERROR', 'data': {'errorcode': 354, 'message': 'Invalid username or password',** 'severity': 'ERROR'}}*

**Comment by sumanth-lingappa** [comment]
@kaplian: Can you please give me more details of your run? such as which template you are trying, your working environment (VPC, subnet details) etc.

Thank you.

**Comment by kaplian** [comment]
Hi All, we can close this out.  The issue I encountered was related to the bootstrap config not being downloaded and applied.  This was due to the AMI I was using was not one included in your script.
