### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by horneian** [citrix/netscaler-aws-cloudformation#6]
unable to ping, ssh or open management UI on completion.  No errors reported, secgroups checked, pther services built in same VPC setup are working just fine.

**Comment by sumanth-lingappa** [comment]
@horneian , can you please provide more information on which template you ran and others?

Thank you.

**Comment by sumanth-lingappa** [comment]
closing this issue. Please reopen if it persists again. 
Also, please provide more information on the template being run.
